name: stella_caeli
description: "Mobile Planetarium & Constellation Visualization App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^7.0.0
  geolocator: ^14.0.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - lib/data/stars.json
    - lib/data/constellations.json
    - assets/icon/icon.png

 
